[global]
# 开发模式
developmentMode = false

[server]
# 端口设置
port = 8501
# 启用CORS
enableCORS = false
# 启用WebSocket压缩
enableWebsocketCompression = true
# 运行状态检查
runOnSave = true
# 文件监控
fileWatcherType = "auto"

[browser]
# 自动打开浏览器
gatherUsageStats = false

[theme]
# 主题设置（可选）
primaryColor = "#FF0D57"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[client]
# 客户端设置
caching = true
displayEnabled = true

[logger]
# 日志级别
level = "info" 